# Background and foreground colors
background = #1d1a34
foreground = #7783ce

# Standard colors
palette = 0=#1d1a34
palette = 1=#f83a64
palette = 2=#60dd59
palette = 3=#fdd054
palette = 4=#3771ff
palette = 5=#aa4efb
palette = 6=#4ddfc8
palette = 7=#7788ec

# Bright colors
palette = 8=#353558
palette = 9=#f83a64
palette = 10=#60dd59
palette = 11=#fdd054
palette = 12=#3771ff
palette = 13=#aa4efb
palette = 14=#4ddfc8
palette = 15=#7783ce
