$color = rgba(29, 26, 52, 1)
$inner_color = rgba(29, 26, 52, 0.66)
$outer_color = rgba(170, 78, 251, 1)
$font_color = rgba(119, 131, 206, 1)
$placeholder_color = rgba(119, 131, 206, 0.7)
$check_color = rgba(77, 223, 200, 1)
