background            #1d1a34
foreground            #7783ce

# black
color0  #1d1a34
color8  #353558

# red
color1  #f83a64
color9  #f83a64

# green
color2  #60dd59
color10 #60dd59

# yellow
color3  #fdd054
color11 #fdd054

# blue
color4  #3771ff
color12 #3771ff

# magenta
color5  #aa4efb
color13 #aa4efb

#cyan
color6  #4ddfc8
color14 #4ddfc8

#white
color7  #7788ec
color15 #7783ce


